# 端口
server:
  port: 8888

spring:
  application:
    name: cloud-config-conter
#  profiles:
    # 告诉服务,我现在要启用本地配置(优先考虑采用工程目录resources下配置)
#    active: native
  cloud:
    config:
      server:
#        native:
#          # 搜索配置文件的位置。默认与Spring Boot应用相同，
#          # [classpath：/，classpath：/ config /，file：./，file：./ config /]。
#          search-locations: /Users/h__d/Documents/git-repository/springcloud-config2
#        composite:
#          - type: native
#            search-locations: /Users/h__d/Documents/git-repository/springcloud-config2
#        # 指示配置服务器应使用远程存储库中的属性初始化其自己的环境的标志。默认情况下处于关闭状态，
#        # 因为它会延迟启动，但是在将服务器嵌入另一个应用程序时很有用。
#        bootstrap: true
        git:
          # git仓库地址
          uri: https://localhost/springcloud-config.git
          username: root
          password: 123456
          # 跳过SSL的验证
          skipSslValidation: true
          # 查找路径，默认在根路径下，以下写法表示在更目录下以及folder目录下查找文件
          searchPaths: folder
          # 本地仓库目录设定
          basedir: /Users/h__d/Documents/git-repository/springcloud-config2

    bus:
      trace:
        ## 开启消息跟踪
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        # 暴露bus刷新端点
        include: "*"