# 端口
server:
  port: 9011

spring:
  application:
    name: seata-order-service
  #   数据源基本配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        # 此处的名称一定要与 vgroup-mapping配置的参数保持一致
        tx-service-group: my_order_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?allowPublicKeyRetrieval=true&useSSL=true
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: ${spring.application.name}-CP
      idle-timeout: 10000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      leakDetectionThreshold: 40000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

# 饿加载开启 Feign 预加载, 防止第一次请求超时
  eager-load:
    enabled: true
    clients: seata-storage-service, storage-account-server

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  # 所有entity别名类所在的包
  type-aliases-pachage: com.test.springcloud.entities

logging:
  level:
    #    root: debug
    com.test.springcloud: debug
#    io.seata: debug
#    org.springframework.cloud.alibaba.seata.web: debug

#seata:
#  enabled: true
#  application-id: ${spring.application.name}  # 可以自定义
#  tx-service-group: my_test_tx_group # 此处的名称一定要与 vgroup-mapping下配置的参数保持一致
#  registry:
#    type: nacos
#    file:
#      name: registry.conf
#  service:
#    grouplist:
#      # seata seaver的 地址配置，此处可以集群配置是个数组
#      default: 127.0.0.1:8091
#      vgroup-mapping:
#        # key一定要与tx-service-group一致
#        my_test_tx_group: default