# 端口
server:
  port: 8010

spring:
  application:
    name: cloud-sleuth-provider
  zipkin:
    # zipkin url地址
#    base-url: http://localhost:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      # 采样率值介于 0 到 1 之间， 1 则表示全部采集
      # 默认值：0.1，即10％
      probability: 1
  #    base-url: http://localhost:9411
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
