# 端口
server:
  port: 8889

spring:
  # RabbitMQ相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        # 暴露刷新端点bus-refresh
#        include: "*"