# 端口
server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway
  cloud:
#    gateway:
#      routes:
#          # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
#        - id: payment_routh
#          # 匹配后提供服务的路由地址
#          uri: http://localhost:8001
#          # 断言，路径相匹配的进行路由
#          predicates:
#            - Path=/payment/get/**
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
          # 路由id
        - id: payment_routh
          # 匹配后提供服务路由地址
          uri: lb://cloud-payment-service
          # 断言
          predicates:
            # curl http://localhost:9527/payment/get/1
            - Path=/payment/get/**

            # After时间断言，时间之后
            # - After=2020-04-21T23:57:57.308+08:00[Asia/Shanghai]

            # Cookie断言，请求必须带cookie，且cookie名为username，值为xiaoming
            # curl http://localhost:9527/payment/get/1 --cookie "username=xiaoming"
            # - Cookie=username, xiaoming

            # Header断言，请求必须带Header，且Header名为X-Request-Id，值为正整数
            # curl http://localhost:9527/payment/get/1 -H "X-Request-Id:123"
            # - Header=X-Request-Id, \d+

            # Host断言，请求必须带主机参数
            # curl http://localhost:9527/payment/get/1 -H "Host:demo1.x.com"
            # - Host=**.x.com

            # Method断言，允许请求方式
            # curl http://localhost:9527/payment/get/1 -X POST
            # curl http://localhost:9527/payment/get/1 -X GET
            # - Method=GET

            # Query断言，请求必须带查询参数
            # curl http://localhost:9527/payment/get/1?green=1
            # - Query=green

            # RemoteAddr断言，允许范围内的远程地址进行访问
            # curl http://192.168.1.4:9527/payment/get/1
            # - RemoteAddr=192.168.1.1/24
#        - id: weight_high
#          uri: http://localhost:8001
#          predicates:
#            - Weight=group1, 8
#        - id: weight_low
#          uri: http://localhost:8002
#          predicates:
#            - Weight=group1, 2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka