# 端口
server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  devtools:
    restart:
      # 解决idea的编译未完成，DevTools的已重启，导致的问题
      # 在轮询类路径更改之间等待的时间量。
      poll-interval: 3000ms
      # 在重新启动之前不更改任何类路径所需的静默时间
      quiet-period: 2999ms
  cloud:
    zookeeper:
      # 集群模式用逗号隔开
      connect-string: localhost:2181

management:
  endpoint:
    shutdown:
      # 启用shutdown，优雅停服功能
      enabled: true
  endpoints:
    web:
      exposure:
        # 暴露shutdown的web端口
        include: shutdown

