# 端口
server:
  port: 7994

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置Sentinel DashBoard地址
        dashboard: localhost:8080
        # 应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        # 默认8719端口，假如端口被占用，依次+1，直到找到未被占用端口
        port: 8719


# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'