# 端口
server:
  port: 9013

spring:
  application:
    name: seata-account-service
  #   数据源基本配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: my_account_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?allowPublicKeyRetrieval=true&useSSL=true
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: ${spring.application.name}-CP
      idle-timeout: 10000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      leakDetectionThreshold: 40000

feign:
  hystrix:
    enabled: true

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  # 所有entity别名类所在的包
  type-aliases-pachage: com.test.springcloud.entities

logging:
  level:
    #    root: debug
    com.test.springcloud: debug
#    io.seata: debug
#    org.springframework.cloud.alibaba.seata.web: debug