# 端口
server:
  port: 7997

spring:
  application:
    name: cloud-order

eureka:
  client:
    # 表示将自己注册进Eureka Server默认为true
    register-with-eureka: true
    # 是否从Eureka Server抓去已有的注册信息，默认是true
    fetch-registry: true
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka8761.com:8761/eureka,http://${spring.security.user.name}:${spring.security.user.password}@eureka8762.com:8762/eureka
  instance:
    #  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 访问路径可以显示IP地址
    prefer-ip-address: true


# 设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的军事家
  ConnectTimeout: 5000


logging:
  level:
    com.test.springcloud.service.PaymentFeignService: debug